[package]
name = "tts-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tts = "0.26.3"        # ou coqui-tts si tu veux direct offline
anyhow = "1"
